# Generated by Django 4.1.6 on 2023-02-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audiofile.category')),
            ],
        ),
        migrations.CreateModel(
            name='audiofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='audio/images/')),
                ('author', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('tags', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio/audiofiles/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiofile.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiofile.subcategory')),
            ],
        ),
    ]
